import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MyThemeProvider from "./components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MyThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100vh] overflow-hidden`}
        >
          <div className="font-[family-name:var(--font-geist-sans)] h-[100vh] flex flex-col overflow-y-auto">
            {children}
          </div>
        </body>
      </MyThemeProvider>
    </html>
  );
}
