import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MyThemeProvider from "./components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MyThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100vh] overflow-x-hidden`}
        >
          <nav className="fixed left-0 top-0 h-12 w-[100vw] border-b">
            {" "}
            Navbar{" "}
          </nav>
          <div className="grid grid-rows-[3rem_1fr_20px] font-[family-name:var(--font-geist-sans)] h-[99vh]">
            <div> </div>
            {children}
            <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center border-t w-full">
              <h1> My footer </h1>
            </footer>
          </div>
        </body>
      </MyThemeProvider>
    </html>
  );
}
